# Generated by Django 6.0.3 on 2026-03-06 10:37

import apps.content_management.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_name_de', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cms_units',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_unit_created')],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_name', models.CharField(max_length=255)),
                ('mission_name_de', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_description_de', models.TextField()),
                ('task', models.TextField()),
                ('task_de', models.TextField()),
                ('video', models.FileField(upload_to=apps.content_management.models.upload_video)),
                ('video_thumbnail', models.ImageField(upload_to=apps.content_management.models.upload_thumbnail)),
                ('task_video', models.FileField(upload_to=apps.content_management.models.upload_task_video)),
                ('task_thumbnail', models.ImageField(upload_to=apps.content_management.models.upload_task_thumbnail)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='content_management.unit')),
            ],
            options={
                'db_table': 'cms_missions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unit', '-created_at'], name='idx_mission_unit')],
            },
        ),
    ]
